### ISSUE TITLE
The binary name is "cli" not "wole"

### ISSUE THREAD

**Issue by saschanaz** [ahmtcn123/Wol#2]
https://github.com/ahmtcn123/Wole/blob/c84e7657bf10eb8f94d4192368d9af0393ff226f/Cargo.toml#L19

I think you intended to make it "wole".

**Comment by ahmetcanaksu** [comment]
Thanks for the advice! 45ab6f593289c9bd43518f303a388633087e2b5f

**Comment by saschanaz** [comment]
Could you also `cargo publish` the new version? Thanks!
